# Generated by Django 4.2.2 on 2024-04-18 11:36

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Company Name')),
            ],
        ),
        migrations.CreateModel(
            name='Dates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=10, unique=True, verbose_name='Date')),
            ],
        ),
        migrations.CreateModel(
            name='Ratios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_shares', models.FloatField(verbose_name='Number of Shares')),
                ('market_price', models.FloatField(verbose_name='Market Price')),
                ('equity', models.FloatField(verbose_name='Total Equity')),
                ('net_income', models.FloatField(verbose_name='Net Income')),
                ('sales', models.FloatField(verbose_name='Sales')),
                ('total_assets', models.FloatField(verbose_name='Total Assets')),
                ('total_equity', models.FloatField(verbose_name='Total Equity')),
                ('ebit', models.FloatField(verbose_name='EBIT')),
                ('intrest', models.FloatField(verbose_name='Interest Expense')),
                ('tax_rate', models.FloatField(verbose_name='Tax Rate')),
                ('dividans', models.FloatField(verbose_name='Dividans')),
                ('total_fixed_assets', models.FloatField(verbose_name='Fixed Assets')),
                ('total_current_assets', models.FloatField(verbose_name='Total Current Assets')),
                ('cogs', models.FloatField(verbose_name='Cost of Revenue, Total')),
                ('inventory', models.FloatField(verbose_name='Total Inventory')),
                ('account_recivables', models.FloatField(verbose_name='Total Receivables, Net')),
                ('account_payable', models.FloatField(verbose_name='Accounts Payable')),
                ('cash', models.FloatField(verbose_name='Cash & Equivalents')),
                ('total_current_liabilty', models.FloatField(verbose_name='Total Current Liabilities')),
                ('total_debt', models.FloatField(verbose_name='Total Debt')),
                ('ebitida', models.FloatField(verbose_name='EBITDA')),
                ('dividansRatio', models.FloatField(default=django.db.models.expressions.CombinedExpression(models.F('dividans'), '/', models.F('net_income')), editable=False, verbose_name='Dividans Ratio')),
                ('book_value', models.FloatField(default=django.db.models.expressions.CombinedExpression(models.F('equity'), '/', models.F('number_of_shares')), editable=False, verbose_name='Book Value')),
                ('eps', models.FloatField(default=django.db.models.expressions.CombinedExpression(models.F('net_income'), '/', models.F('number_of_shares')), editable=False, verbose_name='EPS')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.company')),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.dates')),
            ],
        ),
    ]
